version: 0.2

phases:
  build:
    commands:
      # Create virtual environment, activate, install dependencies, run script with S3 path
      - ls -lah
      - sh -c 'python3 -m venv .venv . .venv/bin/activate; pip install -r requirements.txt; python3 src/porting-advisor.py s3://porting-advisor-bedrock-pipeline-output/; deactivate'

artifacts:
  files:
    - output.txt  # Replace with your actual output filename
