version: 0.2

phases:
  build:
    commands:
      # Create virtual environment, activate, install dependencies, run script with S3 path
      - sh -c '. .venv/bin/activate; pip install -r requirements.txt; s3://porting-advisor-bedrock-pipeline-output/requirements_txt.txt; deactivate'

artifacts:
  files:
    - output.txt  # Replace with your actual output filename
