version: 0.2

phases:
  install:
    commands:
      - aws s3 cp s3://porting-advisor-bedrock-pipeline-output/requirements_txt.txt requirements_txt.txt  # Download requirements file (ensure filename casing matches S3)
      - pip install -r requirements_txt.txt
  build:
    commands:
      - python ./porting_advisor.py  # No need for the -i flag anymore
      - mv advisor_report.txt output.txt  # Replace advisor_report.txt with your actual output filename

artifacts:
  files:
    - output.txt  # Replace with your actual output filename
